### ISSUE TITLE
Minimal Bounding box does not have coincident edge with convex hull.

### ISSUE THREAD

**Issue by jseger** [cansik/LongLiveTheSquare#1]
If I understand correctly, at least one edge of the hull should be coincident with the bounding box.  This doesn't seem to be the case.  Before I dig too far into the algorithm (because I think something is not rotating correctly), I want to make sure that this is an issue and I'm not missing something.

![capture](https://cloud.githubusercontent.com/assets/1662708/21744860/6bac465c-d4ec-11e6-8215-dc4f134d2e42.PNG)

**Comment by cansik** [comment]
Yes you are right, there seems to be a problem. I'll check this.

**Comment by cansik** [comment]
Ok I got the issue. I rotated into the wrong direction (from x-axis away and not towards it). The angle was positive, but should be negative.

```csharp
static double AngleToXAxis (Segment2d s)
{
	var delta = s.A - s.B;
	return -Math.Atan (delta.Y / delta.X);
}
```

Now it seems to be correct:

![image](https://cloud.githubusercontent.com/assets/5220162/21751598/f43b7f8c-d5c9-11e6-8240-79cd8554e282.png)

**Comment by jseger** [comment]
Awesome!  Thank you!
